name: fiap_challenge_project
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.4.0
  cloud_firestore: ^5.3.0
  firebase_auth: ^5.2.0
  google_sign_in: ^6.2.1
  carousel_slider: ^5.0.0
  provider: ^6.1.2
  google_maps_flutter: ^2.9.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true
  assets:
   - images/


